language: python

python:
  - 3.7

install:
  - pip install -r ./requirements/requirements-test.txt

script:
  - pytest -c pytest.ini

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
